services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: helpdesk-rabbitmq
    ports:
      - "5672:5672"    # Puerto AMQP (lo usan los servicios Node)
      - "15672:15672"  # Puerto de RabbitMQ Management (interfaz web)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
